[project]
name = "weather-app"
version = "0.1.0"
description = "Weather app that contains ETL to scrap data from DWD Server and FastAPI for exposing them"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "fastapi>=0.121.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "structlog>=25.5.0",
]

[dependency-groups]
dev = [
    "isort>=7.0.0",
    "ruff>=0.14.3",
]
