[project]
name = "weather-api"
version = "0.1.0"
description = "Weather API Service"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "pydantic-settings",
    "uvicorn",
    "slowapi",
    "aiosqlite",
    "fastapi-filter",
]
